receivers:
  filelog:
    include:
      - /var/log/pods/prod_my-target-pod_49cc7c1fd3702c40b2686ea7486091d3/my-target-pod/1.log

exporters:
  debug:
    verbosity: detailed

connectors:
  otlpjson:

service:
  pipelines:
    logs/raw:
      receivers: [filelog]
      exporters: [otlpjson]
    metrics/otlp:
      receivers: [ otlpjson ]
      exporters: [ debug ]
    logs/otlp:
      receivers: [ otlpjson ]
      exporters: [ debug ]
    traces/otlp:
      receivers: [ otlpjson ]
      exporters: [ debug ]
